language: objective-c
osx_image: xcode7.3
xcode_project: RestGoatee.xcodeproj
xcode_scheme: RestGoatee-Tests
xcode_sdk: iphonesimulator9.3
  - brew update
  - brew upgrade xctool
  - brew install carthage
  - carthage bootstrap --verbose
script:
- xctool -project RestGoatee.xcodeproj -scheme RestGoatee-Tests build test -sdk iphonesimulator9.3 GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
- bash <(curl -s https://codecov.io/bash)
