language: objective-c
osx_image: xcode7.3
xcode_workspace: RestGoatee.xcworkspace
xcode_scheme: RestGoatee-Tests
xcode_sdk: iphonesimulator8.4
script:
- xctool -workspace RestGoatee.xcworkspace -scheme RestGoatee-Tests build test -sdk iphonesimulator8.4 GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
- bash <(curl -s https://codecov.io/bash)
